from __future__ import annotations

from dataclasses import dataclass
import importlib
import numpy as np

try:
    _numba = importlib.import_module("numba")
    njit = _numba.njit
    _NUMBA_AVAILABLE = True
except Exception:  # pragma: no cover - optional dependency
    njit = None
    _NUMBA_AVAILABLE = False


def _should_use_numba(use_numba: bool | None) -> bool:
    if use_numba is None:
        return _NUMBA_AVAILABLE
    return bool(use_numba) and _NUMBA_AVAILABLE


def _coerce_face_id(face_id: int) -> int:
    fid = int(face_id)
    if fid < 1 or fid > 8:
        raise ValueError("face_id must be in [1, 8].")
    return fid


def _coerce_positive_radius(radius: float) -> float:
    rr = float(radius)
    if (not np.isfinite(rr)) or rr <= 0.0:
        raise ValueError("radius must be a finite positive float.")
    return rr


def _coerce_xy_arrays(x: np.ndarray, y: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    xx = np.asarray(x, dtype=float)
    yy = np.asarray(y, dtype=float)
    if xx.shape != yy.shape:
        raise ValueError("x and y must have the same shape.")
    return xx, yy


def _validate_local_face_domain(
    x: np.ndarray,
    y: np.ndarray,
    *,
    radius: float,
    tol: float = 1e-12,
) -> None:
    if np.any(x < -tol) or np.any(y < -tol):
        raise ValueError("Local face chart requires x >= 0 and y >= 0.")
    if np.any((x + y) > (radius + tol)):
        raise ValueError("Local face chart requires x + y <= radius.")


def _normalize_local_chart(
    x: np.ndarray,
    y: np.ndarray,
    *,
    radius: float,
) -> tuple[np.ndarray, np.ndarray]:
    return x / radius, y / radius


# Canonical face-1 local chart vertices in 3D:
# A = (1,0,0), B = (0,1,0), C = (0,0,1)
_CANONICAL_FACE_VERTICES = np.asarray(
    [
        [1.0, 0.0, 0.0],  # A
        [0.0, 1.0, 0.0],  # B
        [0.0, 0.0, 1.0],  # C
    ],
    dtype=float,
)

# Local edge ids (1-based) are tied to local chart constraints:
# edge 1: x = 0    => B -> C
# edge 2: y = 0    => C -> A
# edge 3: x + y = 1 => A -> B
_EDGE_VERTEX_IDS = np.asarray(
    [
        [1, 2],  # B -> C
        [2, 0],  # C -> A
        [0, 1],  # A -> B
    ],
    dtype=np.int64,
)


# Face transforms: face1/face2 are implemented directly.
# Faces 3..8 are generated by symmetry from face1 via these signed permutations.
_FACE_TRANSFORMS = np.asarray(
    [
        [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, 1.0]],    # face 1
        [[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],   # face 2
        [[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, 1.0]],  # face 3
        [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],   # face 4
        [[1.0, 0.0, 0.0], [0.0, 1.0, 0.0], [0.0, 0.0, -1.0]],   # face 5
        [[0.0, -1.0, 0.0], [1.0, 0.0, 0.0], [0.0, 0.0, -1.0]],  # face 6
        [[-1.0, 0.0, 0.0], [0.0, -1.0, 0.0], [0.0, 0.0, -1.0]], # face 7
        [[0.0, 1.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 0.0, -1.0]],  # face 8
    ],
    dtype=float,
)


def _build_neighbor_tables() -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    verts = np.einsum("fij,vj->fvi", _FACE_TRANSFORMS, _CANONICAL_FACE_VERTICES)
    edge_map: dict[tuple[tuple[float, float, float], tuple[float, float, float]], list[tuple[int, int, tuple[float, float, float], tuple[float, float, float]]]] = {}

    for f in range(8):
        for e in range(3):
            a_id, b_id = _EDGE_VERTEX_IDS[e]
            pa = tuple(np.round(verts[f, a_id], 12))
            pb = tuple(np.round(verts[f, b_id], 12))
            key = tuple(sorted((pa, pb)))
            edge_map.setdefault(key, []).append((f, e, pa, pb))

    neighbor_face = np.zeros((8, 3), dtype=np.int64)
    neighbor_edge = np.zeros((8, 3), dtype=np.int64)
    edge_flip = np.zeros((8, 3), dtype=bool)

    for key, entries in edge_map.items():
        if len(entries) != 2:
            raise RuntimeError(f"Invalid atlas edge key {key}: expected 2 faces, got {len(entries)}.")

        (f1, e1, p1a, p1b), (f2, e2, p2a, p2b) = entries
        neighbor_face[f1, e1] = f2 + 1  # 1-based
        neighbor_edge[f1, e1] = e2 + 1
        neighbor_face[f2, e2] = f1 + 1
        neighbor_edge[f2, e2] = e1 + 1

        # Flip is true when the local edge orientation is opposite to the
        # orientation on the paired face.
        flip_12 = (np.allclose(p1a, p2b) and np.allclose(p1b, p2a))
        flip_21 = (np.allclose(p2a, p1b) and np.allclose(p2b, p1a))
        edge_flip[f1, e1] = bool(flip_12)
        edge_flip[f2, e2] = bool(flip_21)

    return neighbor_face, neighbor_edge, edge_flip


_ATLAS_NEIGHBOR_FACE, _ATLAS_NEIGHBOR_EDGE, _ATLAS_EDGE_FLIP = _build_neighbor_tables()


@dataclass(frozen=True)
class OctaSphereAtlas:
    """
    Face adjacency metadata for the 8-face octahedral sphere atlas.

    Attributes
    ----------
    radius : float
        Sphere radius used by this atlas metadata object.
    neighbor_face : np.ndarray
        Shape (8, 3), 1-based neighboring face ids for each local edge.
    neighbor_edge : np.ndarray
        Shape (8, 3), 1-based neighbor local edge ids.
    edge_flip : np.ndarray
        Shape (8, 3), whether edge-node ordering must be reversed.
    """

    radius: float
    neighbor_face: np.ndarray
    neighbor_edge: np.ndarray
    edge_flip: np.ndarray


def build_octa_sphere_atlas(radius: float = 1.0) -> OctaSphereAtlas:
    """
    Build the canonical 8-face octahedral sphere atlas metadata.
    """
    rr = _coerce_positive_radius(radius)
    return OctaSphereAtlas(
        radius=rr,
        neighbor_face=np.array(_ATLAS_NEIGHBOR_FACE, copy=True),
        neighbor_edge=np.array(_ATLAS_NEIGHBOR_EDGE, copy=True),
        edge_flip=np.array(_ATLAS_EDGE_FLIP, copy=True),
    )


def _base_face1_unit_map(u: np.ndarray, v: np.ndarray) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    r = u + v
    phi = np.zeros_like(r)
    nz = r > 1e-14
    phi[nz] = 0.5 * np.pi * (v[nz] / r[nz])

    s = np.sqrt(np.maximum(0.0, 2.0 - r * r))
    A = r * s
    x = A * np.cos(phi)
    y = A * np.sin(phi)
    z = 1.0 - r * r
    return x, y, z


def _base_face1_unit_jacobian(
    u: np.ndarray,
    v: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    r = u + v
    phi = np.zeros_like(r)
    dphi_du = np.zeros_like(r)
    dphi_dv = np.zeros_like(r)
    nz = r > 1e-14
    r2 = r[nz] * r[nz]

    phi[nz] = 0.5 * np.pi * (v[nz] / r[nz])
    dphi_du[nz] = -0.5 * np.pi * v[nz] / r2
    dphi_dv[nz] = 0.5 * np.pi * u[nz] / r2

    s = np.sqrt(np.maximum(0.0, 2.0 - r * r))
    A = r * s
    dA_dr = np.zeros_like(r)
    nzs = s > 1e-14
    dA_dr[nzs] = 2.0 * (1.0 - r[nzs] * r[nzs]) / s[nzs]

    c = np.cos(phi)
    si = np.sin(phi)

    dx_du = dA_dr * c + A * (-si) * dphi_du
    dx_dv = dA_dr * c + A * (-si) * dphi_dv
    dy_du = dA_dr * si + A * (c) * dphi_du
    dy_dv = dA_dr * si + A * (c) * dphi_dv
    dz_du = -2.0 * r
    dz_dv = -2.0 * r

    return dx_du, dx_dv, dy_du, dy_dv, dz_du, dz_dv


def _apply_face_transform(
    face_idx: int,
    x: np.ndarray,
    y: np.ndarray,
    z: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    if face_idx == 0:
        return x, y, z
    if face_idx == 1:
        # Face 2 direct formula from face-1 expression.
        return -y, x, z

    M = _FACE_TRANSFORMS[face_idx]
    xx = M[0, 0] * x + M[0, 1] * y + M[0, 2] * z
    yy = M[1, 0] * x + M[1, 1] * y + M[1, 2] * z
    zz = M[2, 0] * x + M[2, 1] * y + M[2, 2] * z
    return xx, yy, zz


def _apply_face_transform_jacobian(
    face_idx: int,
    dx_du: np.ndarray,
    dx_dv: np.ndarray,
    dy_du: np.ndarray,
    dy_dv: np.ndarray,
    dz_du: np.ndarray,
    dz_dv: np.ndarray,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    if face_idx == 0:
        return dx_du, dx_dv, dy_du, dy_dv, dz_du, dz_dv
    if face_idx == 1:
        # Face 2 direct derivatives.
        # X2=-Y1, Y2=X1, Z2=Z1
        dXdx = -dy_du
        dXdy = -dy_dv
        dYdx = dx_du
        dYdy = dx_dv
        dZdx = dz_du
        dZdy = dz_dv
        return dXdx, dXdy, dYdx, dYdy, dZdx, dZdy

    M = _FACE_TRANSFORMS[face_idx]
    dXdx = M[0, 0] * dx_du + M[0, 1] * dy_du + M[0, 2] * dz_du
    dXdy = M[0, 0] * dx_dv + M[0, 1] * dy_dv + M[0, 2] * dz_dv
    dYdx = M[1, 0] * dx_du + M[1, 1] * dy_du + M[1, 2] * dz_du
    dYdy = M[1, 0] * dx_dv + M[1, 1] * dy_dv + M[1, 2] * dz_dv
    dZdx = M[2, 0] * dx_du + M[2, 1] * dy_du + M[2, 2] * dz_du
    dZdy = M[2, 0] * dx_dv + M[2, 1] * dy_dv + M[2, 2] * dz_dv
    return dXdx, dXdy, dYdx, dYdy, dZdx, dZdy


if _NUMBA_AVAILABLE:
    @njit(cache=True)
    def _map_chart_to_sphere_numba(
        face_idx: int,
        u: np.ndarray,
        v: np.ndarray,
        radius: float,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        n = u.size
        X = np.empty(n, dtype=np.float64)
        Y = np.empty(n, dtype=np.float64)
        Z = np.empty(n, dtype=np.float64)

        M = _FACE_TRANSFORMS[face_idx]
        m00, m01, m02 = M[0, 0], M[0, 1], M[0, 2]
        m10, m11, m12 = M[1, 0], M[1, 1], M[1, 2]
        m20, m21, m22 = M[2, 0], M[2, 1], M[2, 2]

        for i in range(n):
            ui = u[i]
            vi = v[i]
            r = ui + vi

            phi = 0.0
            if r > 1e-14:
                phi = 0.5 * np.pi * (vi / r)

            s = np.sqrt(max(0.0, 2.0 - r * r))
            A = r * s
            x1 = A * np.cos(phi)
            y1 = A * np.sin(phi)
            z1 = 1.0 - r * r

            if face_idx == 0:
                xo = x1
                yo = y1
                zo = z1
            elif face_idx == 1:
                xo = -y1
                yo = x1
                zo = z1
            else:
                xo = m00 * x1 + m01 * y1 + m02 * z1
                yo = m10 * x1 + m11 * y1 + m12 * z1
                zo = m20 * x1 + m21 * y1 + m22 * z1

            X[i] = radius * xo
            Y[i] = radius * yo
            Z[i] = radius * zo

        return X, Y, Z


    @njit(cache=True)
    def _map_chart_jacobian_numba(
        face_idx: int,
        u: np.ndarray,
        v: np.ndarray,
        radius: float,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
        _ = radius  # derivatives are independent of radius in this chart normalization
        n = u.size

        dXdx = np.empty(n, dtype=np.float64)
        dXdy = np.empty(n, dtype=np.float64)
        dYdx = np.empty(n, dtype=np.float64)
        dYdy = np.empty(n, dtype=np.float64)
        dZdx = np.empty(n, dtype=np.float64)
        dZdy = np.empty(n, dtype=np.float64)
        G = np.empty(n, dtype=np.float64)

        M = _FACE_TRANSFORMS[face_idx]
        m00, m01, m02 = M[0, 0], M[0, 1], M[0, 2]
        m10, m11, m12 = M[1, 0], M[1, 1], M[1, 2]
        m20, m21, m22 = M[2, 0], M[2, 1], M[2, 2]

        for i in range(n):
            ui = u[i]
            vi = v[i]
            r = ui + vi
            r2 = r * r

            phi = 0.0
            dphi_du = 0.0
            dphi_dv = 0.0
            if r > 1e-14:
                phi = 0.5 * np.pi * (vi / r)
                dphi_du = -0.5 * np.pi * vi / r2
                dphi_dv = 0.5 * np.pi * ui / r2

            s = np.sqrt(max(0.0, 2.0 - r2))
            A = r * s
            dA_dr = 0.0
            if s > 1e-14:
                dA_dr = 2.0 * (1.0 - r2) / s

            c = np.cos(phi)
            si = np.sin(phi)

            dx_du_1 = dA_dr * c + A * (-si) * dphi_du
            dx_dv_1 = dA_dr * c + A * (-si) * dphi_dv
            dy_du_1 = dA_dr * si + A * c * dphi_du
            dy_dv_1 = dA_dr * si + A * c * dphi_dv
            dz_du_1 = -2.0 * r
            dz_dv_1 = -2.0 * r

            if face_idx == 0:
                tx0 = dx_du_1
                tx1 = dy_du_1
                tx2 = dz_du_1
                ty0 = dx_dv_1
                ty1 = dy_dv_1
                ty2 = dz_dv_1
            elif face_idx == 1:
                # X2=-Y1, Y2=X1, Z2=Z1
                tx0 = -dy_du_1
                tx1 = dx_du_1
                tx2 = dz_du_1
                ty0 = -dy_dv_1
                ty1 = dx_dv_1
                ty2 = dz_dv_1
            else:
                tx0 = m00 * dx_du_1 + m01 * dy_du_1 + m02 * dz_du_1
                tx1 = m10 * dx_du_1 + m11 * dy_du_1 + m12 * dz_du_1
                tx2 = m20 * dx_du_1 + m21 * dy_du_1 + m22 * dz_du_1
                ty0 = m00 * dx_dv_1 + m01 * dy_dv_1 + m02 * dz_dv_1
                ty1 = m10 * dx_dv_1 + m11 * dy_dv_1 + m12 * dz_dv_1
                ty2 = m20 * dx_dv_1 + m21 * dy_dv_1 + m22 * dz_dv_1

            dXdx[i] = tx0
            dXdy[i] = ty0
            dYdx[i] = tx1
            dYdy[i] = ty1
            dZdx[i] = tx2
            dZdy[i] = ty2

            cx = tx1 * ty2 - tx2 * ty1
            cy = tx2 * ty0 - tx0 * ty2
            cz = tx0 * ty1 - tx1 * ty0
            G[i] = np.sqrt(cx * cx + cy * cy + cz * cz)

        return dXdx, dXdy, dYdx, dYdy, dZdx, dZdy, G


    @njit(cache=True)
    def _sphere_transport_coefficients_numba(
        X: np.ndarray,
        Y: np.ndarray,
        Z: np.ndarray,
        dXdx: np.ndarray,
        dXdy: np.ndarray,
        dYdx: np.ndarray,
        dYdy: np.ndarray,
        dZdx: np.ndarray,
        dZdy: np.ndarray,
        Ux: np.ndarray,
        Uy: np.ndarray,
        Uz: np.ndarray,
        radius: float,
        det_eps: float,
    ) -> tuple[np.ndarray, np.ndarray]:
        n = X.size
        a = np.empty(n, dtype=np.float64)
        b = np.empty(n, dtype=np.float64)

        inv_r = 1.0 / radius

        for i in range(n):
            nx = X[i] * inv_r
            ny = Y[i] * inv_r
            nz = Z[i] * inv_r

            u_dot_n = Ux[i] * nx + Uy[i] * ny + Uz[i] * nz
            utx = Ux[i] - u_dot_n * nx
            uty = Uy[i] - u_dot_n * ny
            utz = Uz[i] - u_dot_n * nz

            tx0 = dXdx[i]
            tx1 = dYdx[i]
            tx2 = dZdx[i]

            ty0 = dXdy[i]
            ty1 = dYdy[i]
            ty2 = dZdy[i]

            g11 = tx0 * tx0 + tx1 * tx1 + tx2 * tx2
            g12 = tx0 * ty0 + tx1 * ty1 + tx2 * ty2
            g22 = ty0 * ty0 + ty1 * ty1 + ty2 * ty2
            det = g11 * g22 - g12 * g12

            if det <= det_eps:
                a[i] = np.nan
                b[i] = np.nan
                continue

            rhs1 = utx * tx0 + uty * tx1 + utz * tx2
            rhs2 = utx * ty0 + uty * ty1 + utz * ty2

            inv_det = 1.0 / det
            a[i] = (rhs1 * g22 - rhs2 * g12) * inv_det
            b[i] = (rhs2 * g11 - rhs1 * g12) * inv_det

        return a, b
else:
    _map_chart_to_sphere_numba = None
    _map_chart_jacobian_numba = None
    _sphere_transport_coefficients_numba = None


def map_chart_to_sphere(
    face_id: int,
    x: np.ndarray,
    y: np.ndarray,
    radius: float = 1.0,
    use_numba: bool | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Map local face-chart coordinates (x, y) to sphere coordinates (X, Y, Z).

    Local chart domain on each face:
        x >= 0, y >= 0, x + y <= radius
    """
    fid = _coerce_face_id(face_id)
    rr = _coerce_positive_radius(radius)
    xx, yy = _coerce_xy_arrays(x, y)
    _validate_local_face_domain(xx, yy, radius=rr)
    u, v = _normalize_local_chart(xx, yy, radius=rr)
    face_idx = fid - 1

    if _should_use_numba(use_numba):
        uf = np.ascontiguousarray(u.reshape(-1), dtype=np.float64)
        vf = np.ascontiguousarray(v.reshape(-1), dtype=np.float64)
        Xf, Yf, Zf = _map_chart_to_sphere_numba(face_idx, uf, vf, rr)
        out_shape = xx.shape
        return Xf.reshape(out_shape), Yf.reshape(out_shape), Zf.reshape(out_shape)

    x1, y1, z1 = _base_face1_unit_map(u, v)
    xf, yf, zf = _apply_face_transform(face_idx, x1, y1, z1)
    return rr * xf, rr * yf, rr * zf


def map_chart_jacobian(
    face_id: int,
    x: np.ndarray,
    y: np.ndarray,
    radius: float = 1.0,
    use_numba: bool | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Return local chart Jacobian entries and area factor G.

    Returns
    -------
    dXdx, dXdy, dYdx, dYdy, dZdx, dZdy, G
    """
    fid = _coerce_face_id(face_id)
    rr = _coerce_positive_radius(radius)
    xx, yy = _coerce_xy_arrays(x, y)
    _validate_local_face_domain(xx, yy, radius=rr)
    u, v = _normalize_local_chart(xx, yy, radius=rr)
    face_idx = fid - 1

    if _should_use_numba(use_numba):
        uf = np.ascontiguousarray(u.reshape(-1), dtype=np.float64)
        vf = np.ascontiguousarray(v.reshape(-1), dtype=np.float64)
        dXdxf, dXdyf, dYdxf, dYdyf, dZdxf, dZdyf, Gf = _map_chart_jacobian_numba(
            face_idx,
            uf,
            vf,
            rr,
        )
        out_shape = xx.shape
        return (
            dXdxf.reshape(out_shape),
            dXdyf.reshape(out_shape),
            dYdxf.reshape(out_shape),
            dYdyf.reshape(out_shape),
            dZdxf.reshape(out_shape),
            dZdyf.reshape(out_shape),
            Gf.reshape(out_shape),
        )

    dx_du, dx_dv, dy_du, dy_dv, dz_du, dz_dv = _base_face1_unit_jacobian(u, v)
    dXdx, dXdy, dYdx, dYdy, dZdx, dZdy = _apply_face_transform_jacobian(
        face_idx,
        dx_du,
        dx_dv,
        dy_du,
        dy_dv,
        dz_du,
        dz_dv,
    )

    tx = np.stack([dXdx, dYdx, dZdx], axis=-1)
    ty = np.stack([dXdy, dYdy, dZdy], axis=-1)
    G = np.linalg.norm(np.cross(tx, ty), axis=-1)
    return dXdx, dXdy, dYdx, dYdy, dZdx, dZdy, G


def sphere_transport_coefficients(
    face_id: int,
    x: np.ndarray,
    y: np.ndarray,
    velocity_sphere,
    t: float,
    radius: float = 1.0,
    use_numba: bool | None = None,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """
    Build chart coefficients (a, b) for surface transport velocity.

    Parameters
    ----------
    velocity_sphere : callable
        Interface:
            velocity_sphere(X, Y, Z, t) -> (Ux, Uy, Uz)
    """
    rr = _coerce_positive_radius(radius)
    X, Y, Z = map_chart_to_sphere(face_id=face_id, x=x, y=y, radius=rr, use_numba=use_numba)
    dXdx, dXdy, dYdx, dYdy, dZdx, dZdy, G = map_chart_jacobian(
        face_id=face_id,
        x=x,
        y=y,
        radius=rr,
        use_numba=use_numba,
    )

    Ux, Uy, Uz = velocity_sphere(X, Y, Z, t)
    Ux = np.asarray(Ux, dtype=float)
    Uy = np.asarray(Uy, dtype=float)
    Uz = np.asarray(Uz, dtype=float)
    if Ux.shape != X.shape or Uy.shape != X.shape or Uz.shape != X.shape:
        raise ValueError("velocity_sphere must return arrays with the same shape as x/y.")

    if _should_use_numba(use_numba):
        Xf = np.ascontiguousarray(X.reshape(-1), dtype=np.float64)
        Yf = np.ascontiguousarray(Y.reshape(-1), dtype=np.float64)
        Zf = np.ascontiguousarray(Z.reshape(-1), dtype=np.float64)
        dXdx_f = np.ascontiguousarray(dXdx.reshape(-1), dtype=np.float64)
        dXdy_f = np.ascontiguousarray(dXdy.reshape(-1), dtype=np.float64)
        dYdx_f = np.ascontiguousarray(dYdx.reshape(-1), dtype=np.float64)
        dYdy_f = np.ascontiguousarray(dYdy.reshape(-1), dtype=np.float64)
        dZdx_f = np.ascontiguousarray(dZdx.reshape(-1), dtype=np.float64)
        dZdy_f = np.ascontiguousarray(dZdy.reshape(-1), dtype=np.float64)
        Ux_f = np.ascontiguousarray(Ux.reshape(-1), dtype=np.float64)
        Uy_f = np.ascontiguousarray(Uy.reshape(-1), dtype=np.float64)
        Uz_f = np.ascontiguousarray(Uz.reshape(-1), dtype=np.float64)

        af, bf = _sphere_transport_coefficients_numba(
            Xf,
            Yf,
            Zf,
            dXdx_f,
            dXdy_f,
            dYdx_f,
            dYdy_f,
            dZdx_f,
            dZdy_f,
            Ux_f,
            Uy_f,
            Uz_f,
            rr,
            1e-14,
        )
        a = af.reshape(X.shape)
        b = bf.reshape(X.shape)
    else:
        nx = X / rr
        ny = Y / rr
        nz = Z / rr
        u_dot_n = Ux * nx + Uy * ny + Uz * nz
        Utx = Ux - u_dot_n * nx
        Uty = Uy - u_dot_n * ny
        Utz = Uz - u_dot_n * nz

        g11 = dXdx * dXdx + dYdx * dYdx + dZdx * dZdx
        g12 = dXdx * dXdy + dYdx * dYdy + dZdx * dZdy
        g22 = dXdy * dXdy + dYdy * dYdy + dZdy * dZdy
        det = g11 * g22 - g12 * g12

        rhs1 = Utx * dXdx + Uty * dYdx + Utz * dZdx
        rhs2 = Utx * dXdy + Uty * dYdy + Utz * dZdy

        a = np.full_like(det, np.nan, dtype=float)
        b = np.full_like(det, np.nan, dtype=float)
        ok = det > 1e-14
        a[ok] = (rhs1[ok] * g22[ok] - rhs2[ok] * g12[ok]) / det[ok]
        b[ok] = (rhs2[ok] * g11[ok] - rhs1[ok] * g12[ok]) / det[ok]

    if np.any(~np.isfinite(a)) or np.any(~np.isfinite(b)):
        raise ValueError(
            "Degenerate local metric encountered while computing transport coefficients; "
            "avoid apex/seam chart points."
        )

    return X, Y, Z, a, b, G


def tag_square_chart_faces(
    x: np.ndarray,
    y: np.ndarray,
    radius: float = 1.0,
    tol: float = 1e-12,
) -> np.ndarray:
    """
    Tag global square-chart coordinates by octa-sphere face id.

    Input domain:
        x, y in [-radius, radius]

    Returns
    -------
    np.ndarray of ints
        face id in {1..8} for non-seam points.
        seam points (|x|+|y| == radius) are tagged as 0.
    """
    rr = _coerce_positive_radius(radius)
    xx, yy = _coerce_xy_arrays(x, y)

    if np.any(np.abs(xx) > rr + tol) or np.any(np.abs(yy) > rr + tol):
        raise ValueError("Square chart requires x,y in [-radius, radius].")

    u = xx / rr
    v = yy / rr
    su = np.abs(u)
    sv = np.abs(v)
    level = su + sv

    seam = np.abs(level - 1.0) <= tol
    top = level < (1.0 - tol)

    quad = np.empty_like(level, dtype=np.int64)
    quad[(u >= 0.0) & (v >= 0.0)] = 0
    quad[(u < 0.0) & (v >= 0.0)] = 1
    quad[(u < 0.0) & (v < 0.0)] = 2
    quad[(u >= 0.0) & (v < 0.0)] = 3

    face = np.where(top, quad + 1, quad + 5).astype(np.int64)
    face[seam] = 0
    return face


def validate_elements_single_face(
    x_nodes: np.ndarray,
    y_nodes: np.ndarray,
    radius: float = 1.0,
    tol: float = 1e-12,
) -> np.ndarray:
    """
    Validate that each element's chart nodes lie in one and only one face.

    Parameters
    ----------
    x_nodes, y_nodes : np.ndarray
        Shape (K, Np)

    Returns
    -------
    np.ndarray
        Shape (K,), per-element face id (1..8)
    """
    xx, yy = _coerce_xy_arrays(x_nodes, y_nodes)
    if xx.ndim != 2:
        raise ValueError("x_nodes and y_nodes must have shape (K, Np).")

    face = tag_square_chart_faces(xx, yy, radius=radius, tol=tol)
    if np.any(face == 0):
        seam_rows = np.unique(np.where(face == 0)[0]).tolist()
        raise ValueError(
            "Found seam nodes (|x|+|y|==radius) while assigning element face ids; "
            f"affected elements: {seam_rows}."
        )

    face0 = face[:, 0]
    mixed = np.where(np.any(face != face0[:, None], axis=1))[0]
    if mixed.size > 0:
        raise ValueError(
            "Elements crossing atlas seams are not allowed in this v1 mapping path; "
            f"mixed-face elements: {mixed.tolist()}."
        )

    return face0


def build_cross_face_edge_pairs(
    nfp: int,
    atlas: OctaSphereAtlas | None = None,
) -> dict[str, np.ndarray]:
    """
    Build cross-face edge pairing data with edge-node permutations.

    This output can be consumed by future exchange-trace coupling code.
    """
    if nfp < 1:
        raise ValueError("nfp must be >= 1.")

    atlas_obj = build_octa_sphere_atlas() if atlas is None else atlas
    neighbor_face = np.asarray(atlas_obj.neighbor_face, dtype=np.int64)
    neighbor_edge = np.asarray(atlas_obj.neighbor_edge, dtype=np.int64)
    edge_flip = np.asarray(atlas_obj.edge_flip, dtype=bool)

    if neighbor_face.shape != (8, 3) or neighbor_edge.shape != (8, 3) or edge_flip.shape != (8, 3):
        raise ValueError("atlas neighbor arrays must all have shape (8, 3).")

    face_a_list: list[int] = []
    edge_a_list: list[int] = []
    face_b_list: list[int] = []
    edge_b_list: list[int] = []
    flip_list: list[bool] = []
    node_a_list: list[np.ndarray] = []
    node_b_list: list[np.ndarray] = []

    seen: set[tuple[tuple[int, int], tuple[int, int]]] = set()
    base_ids = np.arange(nfp, dtype=np.int64)

    for f in range(8):
        for e in range(3):
            g = int(neighbor_face[f, e] - 1)
            ge = int(neighbor_edge[f, e] - 1)
            key = tuple(sorted(((f, e), (g, ge))))
            if key in seen:
                continue
            seen.add(key)

            flip = bool(edge_flip[f, e])
            ids_a = base_ids
            ids_b = base_ids[::-1] if flip else base_ids

            face_a_list.append(f + 1)
            edge_a_list.append(e + 1)
            face_b_list.append(g + 1)
            edge_b_list.append(ge + 1)
            flip_list.append(flip)
            node_a_list.append(ids_a.copy())
            node_b_list.append(ids_b.copy())

    return {
        "face_a": np.asarray(face_a_list, dtype=np.int64),
        "edge_a": np.asarray(edge_a_list, dtype=np.int64),
        "face_b": np.asarray(face_b_list, dtype=np.int64),
        "edge_b": np.asarray(edge_b_list, dtype=np.int64),
        "edge_flip": np.asarray(flip_list, dtype=bool),
        "node_ids_a": np.asarray(node_a_list, dtype=np.int64),
        "node_ids_b": np.asarray(node_b_list, dtype=np.int64),
    }


__all__ = [
    "OctaSphereAtlas",
    "build_octa_sphere_atlas",
    "map_chart_to_sphere",
    "map_chart_jacobian",
    "sphere_transport_coefficients",
    "tag_square_chart_faces",
    "validate_elements_single_face",
    "build_cross_face_edge_pairs",
]
